export const GET_DRIVERS = "GET_DRIVERS";
export const GET_DRIVER_BY_ID = "GET_DRIVER_BY_ID";
export const GET_DRIVER_DETAIL = "GET_DRIVER_DETAIL";
export const GET_DRIVERS_BY_NAME = "GET_DRIVERS_BY_NAME";
export const GET_DRIVERS_BY_TEAM = "GET_DRIVERS_BY_TEAM";

export const SORT_DRIVERS_BY_NAME = "SORT_DRIVERS_BY_NAME";
export const SORT_DRIVERS_BY_BIRTHDATE = "SORT_DRIVERS_BY_BIRTHDATE";

export const CREATE_DRIVER = "CREATE_DRIVER";
export const UPDATE_DRIVER = "UPDATE_DRIVER";
export const DELETE_DRIVER = "DELETE_DRIVER";